//This is a theme file, please update any theme related constants here

const COLOR_SECONDARY = '#A2EE43';
const COLOR_DARK = '#000000';
const COLOR_DEFAULT = '#333333';
const COLOR_DEFAULT_LIGHT = '#666666';
const COLOR_LIGHTER = '#AAAAAA';
const COLOR_LIGHTEST = '#DDDDDD';
const COLOR_BRIGHT = '#FFFFFF';
const COLOR_DANGER = '#E31912';

export const commonTheme = {
  COLOR_DANGER: COLOR_DANGER,
  COLOR_SECONDARY: COLOR_SECONDARY,
  COLOR_DEFAULT: COLOR_DEFAULT,
  COLOR_DARK: COLOR_DARK,
  COLOR_DEFAULT_LIGHT: COLOR_DEFAULT_LIGHT,
  COLOR_LIGHTEST: COLOR_LIGHTEST,
  COLOR_DISABLED: COLOR_LIGHTER,
  COLOR_HINT: COLOR_LIGHTEST,
  COLOR_BRIGHT: COLOR_BRIGHT,
  FONT_LIGHT: 'Roboto-Light',
  FONT_MEDIUM: 'Roboto-Medium',
  FONT_REGULAR: 'Roboto-Regular',
  FONT_BOLD: 'Roboto-Bold',
  TEXT_SIZE_EXTRA_SMALL: 12,
  TEXT_SIZE_SMALL: 14,
  TEXT_SIZE_DEFAULT: 16,
  TEXT_SIZE_MEDIUM: 18,
  TEXT_SIZE_LARGE: 20,
  TEXT_SIZE_EXTRA_LARGE: 32,
};
